### ISSUE TITLE
Error while loading animation

### ISSUE THREAD

**Issue by arrowoliver** [2d-inc/Flare-Flutter#15]
Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (30584): more information in this error message to help you determine and fix the underlying cause.
I/flutter (30584): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (30584):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (30584):
I/flutter (30584): When the exception was thrown, this was the stack:
I/flutter (30584): #2      Color.withOpacity (dart:ui/painting.dart:187:12)
I/flutter (30584): #3      FlutterGradientFill.getPaint (package:flarepack/flare.dart:239:30)
I/flutter (30584): #4      FlutterActorShape.draw (package:flarepack/flare.dart:126:31)
I/flutter (30584): #5      FlutterActorArtboard.draw (package:flarepack/flare.dart:526:18)
I/flutter (30584): #6      FlareActorRenderObject.paint (package:flarepack/flare_actor.dart:422:17)
I/flutter (30584): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2088:7)
I/flutter (30584): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (30584): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter (30584): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2088:7)
I/flutter (30584): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (30584): #12     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (30584): #13     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
I/flutter (30584): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2088:7)
I/flutter (30584): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (30584): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter (30584): #17     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1955:11)
I/flutter (30584): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2088:7)
I/flutter (30584): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (30584): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter (30584): #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2088:7)
I/flutter (30584): #22     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (30584): #23     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (30584): #24     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:855:29)
I/flutter (30584): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:283:19)
I/flutter (30584): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (30584): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (30584): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (30584): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (30584): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (30584): #31     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (30584): #32     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (30584): (elided 2 frames from class _AssertionError)

Animation file from flare  is  https://www.2dimensions.com/a/sagarshah/files/flare/logo_flutter

**Comment by dhuma1981** [comment]
Can you please share your code?

**Comment by luigi-rosso** [comment]
Even just a one liner with your FlareActor constructor would suffice!

**Comment by arrowoliver** [comment]
@dhuma1981 
Here is the snippet.
Just Exploring. A couple of others are working with the same code and replacing the name of the file.

Widget _getFlutterLogoAnimation() {
    return Container(
      color: Colors.lightBlueAccent,
      child: Column(
        children: <Widget>[
          Container(
            width: 400.0,
            height: 400.0,
            child: FlareActor(
              "assets/logo_flutter.flr",
              animation: _animationLogo,
            ),
          ),
        ],
      ),
    );
  }

Please have a look.
