### ISSUE TITLE
The getter 'time' was called on null.

### ISSUE THREAD

**Issue by liujiakuoyx** [2d-inc/Flare-Flutter#209]
[ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
E/flutter (13156): NoSuchMethodError: The getter 'time' was called on null.
E/flutter (13156): Receiver: null
E/flutter (13156): Tried calling: time
E/flutter (13156): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (13156): #1      PropertyAnimation.apply (package:flare_dart/animation/actor_animation.dart:192:35)
E/flutter (13156): #2      ComponentAnimation.apply (package:flare_dart/animation/actor_animation.dart:257:27)
E/flutter (13156): #3      ActorAnimation.apply (package:flare_dart/animation/actor_animation.dart:411:26)
E/flutter (13156): #4      FlareActorRenderObject._updateAnimation (package:flare_flutter/flare_actor.dart:431:19)
E/flutter (13156): #5      FlareActorRenderObject._instanceArtboard (package:flare_flutter/flare_actor.dart:289:5)
E/flutter (13156): #6      FlareActorRenderObject.coldLoad (package:flare_flutter/flare_actor.dart:323:5)
E/flutter (13156): <asynchronous suspension>
E/flutter (13156): #7      FlareRenderBox.load (package:flare_flutter/flare_render_box.dart:272:7)
E/flutter (13156): #8      FlareRenderBox.attach (package:flare_flutter/flare_render_box.dart:115:7)
E/flutter (13156): #9      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
E/flutter (13156): #10     RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1232:11)
E/flutter (13156): #11     RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2879:7)
E/flutter (13156): #12     SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:5142:18)
E/flutter (13156): #13     RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4986:35)
E/flutter (13156): #14     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4752:5)
E/flutter (13156): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13156): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13156): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (13156): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (13156): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (13156): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (13156): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13156): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13156): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (13156): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (13156): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (13156): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter (13156): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (13156): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13156): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13156): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (13156): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (13156): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (13156): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter (13156): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (13156): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13156): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13156): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (13156): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (13156): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (13156): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (13156): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13156): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13156): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (13156): #44     Element.inflateWidget (package:flutter/src/widgets/fra

Flutter version：
    • Flutter version 1.9.1+hotfix.6 at D:\flutter_sdk\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

    flare_flutter: 1.8.3

**Comment by liujiakuoyx** [comment]
https://rive.app/a/KRay/files/flare/ready-go
