### ISSUE TITLE
LateInitializationError: Field '_setupAABB@43245341' has not been initialized

### ISSUE THREAD

**Issue by jamesc12323** [2d-inc/Flare-Flutter#315]

**Comment by jamesc12323** [comment]
The errors:

The following LateError was thrown during a scheduler callback:
LateInitializationError: Field '_rateAnimation@46307606' has not been initialized.

When the exception was thrown, this was the stack: 
#0      FlareRateController._rateAnimation (package:joran_app/Screens/ChatModule/ChatRateUserScreen/components/FlareController.dart)
#1      FlareRateController.advance (package:joran_app/Screens/ChatModule/ChatRateUserScreen/components/FlareController.dart:25:11)
#2      FlareActorRenderObject.advance (package:flare_flutter/flare_actor.dart:384:23)
#3      FlareRenderBox._beginFrame (package:flare_flutter/flare_render_box.dart:288:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1056:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1054:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:975:5)
#12     _invoke1 (dart:ui/hooks.dart:185:10)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#14     _beginFrame (dart:ui/hooks.dart:116:31)
(elided 3 frames from dart:async)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:521:49)
#3      FlareRenderBox.paint (package:flare_flutter/flare_render_box.dart:170:38)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#9      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2794:15)
#10     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#13     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2794:15)
#14     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:409:5)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#18     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:553:11)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#22     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#23     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1941:15)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#28     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#29     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#30     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#31     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#32     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#33     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#34     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#35     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#36     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#40     _invoke (dart:ui/hooks.dart:166:10)
#41     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#42     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _FrameCallbackEntry and dart:async)
