### ISSUE TITLE
image png error!

### ISSUE THREAD

**Issue by billjone** [2d-inc/Flare-Flutter#61]
when I add a png image ,there is an error.

E/flutter (11979): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'ActorNode' is not a subtype of type 'ActorDrawable' in type cast
E/flutter (11979): #0      KeyFrameDrawOrder.apply (package:flare_dart/animation/keyframe.dart:450:61)
E/flutter (11979): #1      PropertyAnimation.apply (package:flare_dart/animation/actor_animation.dart:199:21)
E/flutter (11979): #2      ComponentAnimation.apply (package:flare_dart/animation/actor_animation.dart:248:27)
E/flutter (11979): #3      ActorAnimation.apply (package:flare_dart/animation/actor_animation.dart:403:26)
E/flutter (11979): #4      FlareActorRenderObject._updateAnimation (package:flare_flutter/flare_actor.dart:471:19)
E/flutter (11979): #5      FlareActorRenderObject.filename=.<anonymous closure> (package:flare_flutter/flare_actor.dart:248:11)
E/flutter (11979): #6      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (11979): #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (11979): #8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (11979): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (11979): #10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (11979): #11     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (11979): #12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (11979): #13     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
E/flutter (11979): #14     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
E/flutter (11979): #15     Actor.load (package:flare_dart/actor.dart)
E/flutter (11979): <asynchronous suspension>
E/flutter (11979): #16     FlutterActor.loadFromBundle (package:flare_flutter/flare.dart:595:18)
E/flutter (11979): <asynchronous suspension>
E/flutter (11979): #17     FlareActorRenderObject.filename= (package:flare_flutter/flare_actor.dart:228:13)
E/flutter (11979): #18     FlareActor.createRenderObject (package:flare_flutter/flare_actor.dart:43:9)
E/flutter (11979): #19     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4497:28)
E/flutter (11979): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter (11979): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter (11979): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter (11979): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter (11979): #24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4981:32)
E/flutter (11979): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter (11979): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter (11979): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
E/flutter (11979): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
E/flutter (11979): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
E/flutter (11979): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863:11)
E/flutter (11979): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
E/flutter (11979): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter (11979): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter (11979): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter (11979): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter (11979): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter (11979): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746:16)
E/flutter (11979): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
E/flutter (11979): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
E/flutter (11979): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
E/flutter (11979): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter (11979): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter (11979): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875:14)
E/flutter (11979): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
E/flutter (11979): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2757:12)
E/flutter (11979): #46     SingleChildRenderObjectElement.mou
I/AwareBitmapCacher(11979): init lrucache size: 2097152 pid=11979
I/.dx.flutterapp(11979): Starting profile saver IsSaveProfileNow end.

**Comment by umberto-sonnino** [comment]
Hey @billjone, could you share the file that's crashing?

**Comment by billjone** [comment]
thi is the flr file url:   https://www.2dimensions.com/a/billjone/files/flare/new-file/preview

and this is the code of my dart:
 child: new FlareActor("animations/flare.flr", animation: "Untitled"),

**Comment by billjone** [comment]
@umberto-sonnino  hello 
this is the project
https://github.com/billjone/flutter_app2

**Comment by luigi-rosso** [comment]
This should be fixed in flare_flutter 1.3.5, please update your pubspec.yaml and let us know!

**Comment by billjone** [comment]
It's OK.
