### ISSUE TITLE
Getting an error when trying to implement the teddy bear

### ISSUE THREAD

**Issue by HElwy** [2d-inc/Flare-Flutter#74]
Was trying to implement the teddy bear example into my app, the teddy doesn't appear, and I get an exception whenever I run it, the only difference that I might have is that I added the flare_flutter by adding `flare_flutter: ^1.3.12` to the `pubspec.yaml`

> I/flutter ( 4149): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4149): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter ( 4149): The getter 'translation' was called on null.
I/flutter ( 4149): Receiver: null
I/flutter ( 4149): Tried calling: translation
I/flutter ( 4149): 
I/flutter ( 4149): When the exception was thrown, this was the stack:
I/flutter ( 4149): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 4149): #1      TeddyController.advance (package:tots_flutter/teddy_controller.dart:66:61)
I/flutter ( 4149): #2      FlareActorRenderObject.advance (package:flare_flutter/flare_actor.dart:304:22)
I/flutter ( 4149): #3      FlareRenderBox._beginFrame (package:flare_flutter/flare_render_box.dart:101:5)
I/flutter ( 4149): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 4149): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:904:11)
I/flutter ( 4149): #6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
I/flutter ( 4149): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:902:17)
I/flutter ( 4149): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:832:5)
I/flutter ( 4149): #12     _invoke1 (dart:ui/hooks.dart:223:10)
I/flutter ( 4149): #13     _beginFrame (dart:ui/hooks.dart:162:3)
I/flutter ( 4149): (elided 3 frames from package dart:async)
I/flutter ( 4149): 
I/flutter ( 4149): 
I/flutter ( 4149): This exception was thrown in the context of a scheduler callback. When the scheduler callback was
I/flutter ( 4149): _registered_ (as opposed to when the exception was thrown), this was the stack:
I/flutter ( 4149): #0      new _FrameCallbackEntry.<anonymous closure> (package:flutter/src/scheduler/binding.dart:108:33)
I/flutter ( 4149): #1      new _FrameCallbackEntry (package:flutter/src/scheduler/binding.dart:111:6)
I/flutter ( 4149): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:424:49)
I/flutter ( 4149): #3      FlareRenderBox.paint (package:flare_flutter/flare_render_box.dart:121:37)
I/flutter ( 4149): #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #6      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4149): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #12     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 4149): #13     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
I/flutter ( 4149): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #16     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4149): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #19     _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:522:17)
I/flutter ( 4149): #20     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 4149): #21     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:394:7)
I/flutter ( 4149): #22     _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:526:17)
I/flutter ( 4149): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #24     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4149): #25     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4149): #26     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4149): #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4149): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #35     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2629:11)
I/flutter ( 4149): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #46     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4149): #47     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4149): #48     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4149): #49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4149): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #51     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:562:11)
I/flutter ( 4149): #52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #56     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4149): #57     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4149): #58     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4149): #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4149): #60     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 4149): #61     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:594:5)
I/flutter ( 4149): #62     RenderStack.paint (package:flutter/src/rendering/stack.dart:602:7)
I/flutter ( 4149): #63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #65     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 4149): #66     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter ( 4149): #67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #70     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:504:11)
I/flutter ( 4149): #71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #74     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 4149): #75     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1717:17)
I/flutter ( 4149): #76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #79     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #83     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4149): #84     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4149): #85     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4149): #86     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4149): #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #90     RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:910:17)
I/flutter ( 4149): #91     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #92     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #94     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2448:13)
I/flutter ( 4149): #95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #97     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #99     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4149): #100    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4149): #101    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4149): #102    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4149): #103    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #104    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #105    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #106    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #107    RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3045:11)
I/flutter ( 4149): #108    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #109    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #110    _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 4149): #111    RenderStack.paintStack (package:flutter/src/rendering/stack.dart:594:5)
I/flutter ( 4149): #112    RenderStack.paint (package:flutter/src/rendering/stack.dart:602:7)
I/flutter ( 4149): #113    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #114    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #115    __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #116    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #117    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #118    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #119    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #120    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #121    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #122    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #123    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #124    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #125    RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2629:11)
I/flutter ( 4149): #126    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #127    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #128    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #129    RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:562:11)
I/flutter ( 4149): #130    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #131    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #132    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4149): #133    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #134    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4149): #135    RenderView.paint (package:flutter/src/rendering/view.dart:182:15)
I/flutter ( 4149): #136    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4149): #137    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4149): #138    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4149): #139    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:853:29)
I/flutter ( 4149): #140    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:331:19)
I/flutter ( 4149): #141    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 4149): #142    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 4149): #143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 4149): #144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 4149): #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
I/flutter ( 4149): #154    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 4149): #155    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 4149): #156    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 4149): (elided 8 frames from package dart:async)
I/flutter ( 4149): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by luigi-rosso** [comment]
If you're using the source from this repository, make sure you've grabbed the latest example as there were breaking changes in the last two releases. This was a mistake on my part, I published them as patches instead of new version changes.

I just tested with 1.3.12, the latest teddy seems to be working here.

**Comment by HElwy** [comment]
What i did yesterday was copying the lib and assets directories to a new flutter project, is that the latest example or there is another branch I should be getting the files from? This is my pubspec, if there is anything else I can do to help us troubleshoot I will supply it

> version:
 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.3.12
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

**Comment by luigi-rosso** [comment]
Sorry I missed this, are you still having problems running this?

**Comment by HElwy** [comment]
I wrote a simplistic login page for my app after I didn't get a response and couldn't get it to work, may try to implement this again after launching.
